USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_ETL;
USE DATABASE NYC_NULL_BOROUGH_FIX;
USE SCHEMA BOROUGH_CURATED;

CREATE OR REPLACE VIEW V_COLLISIONS_BY_HOUR AS
SELECT 
    DATE_PART('HOUR', "CRASH TIME") AS HOUR_OF_DAY,
    COUNT(*) AS TOTAL_COLLISIONS
FROM NYC_MOTOR_VEHICLE_COLLISIONS
GROUP BY 1;
