CREATE TABLE nyc_motor_vehicle_collisions (
    collision_id BIGINT PRIMARY KEY,
    crash_date DATE,
    crash_time TIME,
    borough VARCHAR(50),
    zip_code VARCHAR(10),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location VARCHAR(100),
    on_street_name VARCHAR(100),
    cross_street_name VARCHAR(100),
    off_street_name VARCHAR(100),
    number_of_persons_injured INT,
    number_of_persons_killed INT,
    number_of_pedestrians_injured INT,
    number_of_pedestrians_killed INT,
    number_of_cyclist_injured INT,
    number_of_cyclist_killed INT,
    number_of_motorist_injured INT,
    number_of_motorist_killed INT,
    contributing_factor_vehicle_1 VARCHAR(100),
    contributing_factor_vehicle_2 VARCHAR(100),
    contributing_factor_vehicle_3 VARCHAR(100),
    contributing_factor_vehicle_4 VARCHAR(100),
    contributing_factor_vehicle_5 VARCHAR(100),
    vehicle_type_code_1 VARCHAR(100),
    vehicle_type_code_2 VARCHAR(100),
    vehicle_type_code_3 VARCHAR(100),
    vehicle_type_code_4 VARCHAR(100),
    vehicle_type_code_5 VARCHAR(100)
);